service: api-sim-repo

provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:Get*"
      Resource: "*"

# you can add packaging information here
package:
  exclude:
    - env/

functions:
  main:
    environment: ${file(./env.yml)}
    handler: handler.handle
    events:
      - http:
          path: repo/similar
          method: get
          cors: true
