service: api-sim-repo

provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:Get*"
      Resource: "*"
    - Effect: "Allow"
      Action: "secretsmanager:GetSecretValue"
      Resource: "arn:aws:secretsmanager:*:*:secret:mongodb_credential-FNzCJl"

# you can add packaging information here
package:
  exclude:
    - env/

functions:
  main:
    handler: handler.handle
    events:
      - http:
          path: repo/similar
          method: get
          cors: true
