version: 2
jobs:
  build:
    docker:
      - image: max0ne/circleci-node-aws:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: front_node_modules-{{ checksum "front/package-lock.json" }}
      - run: cd front && npm i
      - save_cache:
          name: Save node modules cache
          key: front_node_modules-{{ checksum "front/package-lock.json" }}
          paths:
            - front/node_modules
      - run: cd front && npm run build-dev
      - run:
          name: Deploy to S3
          command: aws s3 cp front/build s3://twinkeydow-dev.mingfei.me/ --recursive

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
