version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: front_node_modules-{{ checksum "front/package-lock.json" }}
      - run: cd front && npm i
      - save_cache:
          name: Save node modules cache
          key: front_node_modules-{{ checksum "front/package-lock.json" }}
          paths:
            - front/node_modules
      - run: cd front && npm run build-dev
