version: 2
jobs:
  prepare:
    working_directory: front
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: front_node_modules-{{ checksum "package-lock.json" }}
      - run: npm i
      - save_cache:
          name: Save node modules cache
          key: front_node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  build:
    working_directory: front
    docker:
      - image: circleci/node:latest
    steps:
      - run: npm run build-dev
